import "./globals.css";
import LoadingWrapper from "./LoadingWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className=" lg:w-[40%] w-full ">
          <LoadingWrapper>{children}</LoadingWrapper>
        </main>
      </body>
    </html>
  );
}
