import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { BsFillQuestionCircleFill } from "react-icons/bs";
import { FaDropbox } from "react-icons/fa";
import Gallery from "@/components/Gallery";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className} bg-gray-950 bg-opacity-85 flex lg:flex-row justify-between py-10 px-5 `}
      >
        <section className=" hidden lg:block flex-1 "></section>

        <main className=" lg:w-[40%] w-full ">
          <div className=" w-full bg-gray-900 bg-opacity-35 p-3 rounded-xl flex gap-2  ">
            <div>
              <BsFillQuestionCircleFill className=" text-xl text-gray-600 " />
              <div className=" h-[80%] flex items-center justify-center ">
                <FaDropbox className=" text-xl text-gray-600 " />
              </div>
            </div>
            <div className=" w-full">
              <Navbar />
              <div className=" h-[250px] mt-8 p-2 overflow-y-scroll  scrollbar-thin custom-scrollbar scrollbar-thumb-gray-700 scrollbar-track-[#1f1f1f59]   ">
                {children}
              </div>
            </div>
          </div>

          {/* divider */}
          <div className=" w-[80%] mx-auto mt-5 mb-5 border-t-4 border-t-[#1b2430] shadow-lg "></div>

          <div className=" w-full bg-gray-900 bg-opacity-35 p-3 rounded-xl flex gap-2  ">
            <div>
              <BsFillQuestionCircleFill className=" text-xl text-gray-600 " />
              <div className=" h-[80%] flex items-center justify-center ">
                <FaDropbox className=" text-xl text-gray-600 " />
              </div>
            </div>
            <div className=" w-full">
              <Gallery />
            </div>
          </div>
          {/* divider */}
          <div className=" w-[80%] mx-auto mt-5 mb-5 border-t-4 border-t-[#1b2430] shadow-lg "></div>
        </main>
      </body>
    </html>
  );
}
